### ISSUE TITLE
sudo python start_inspector.py -> __init__.py:  invalid syntax

### ISSUE THREAD

**Issue by MadBowkey** [nyu-mlab/iot-inspector-client#107]
-> sudo python start_inspector.py
```
Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
    import inspector
  File "/home/pi/iot-inspector-client/src/inspector.py", line 13, in <module>
    from netdisco_wrapper import NetdiscoWrapper
  File "/home/pi/iot-inspector-client/src/netdisco_wrapper.py", line 13, in <module>
    from netdisco.discovery import NetworkDiscovery
  File "/usr/local/lib/python2.7/dist-packages/netdisco/discovery.py", line 7, in <module>
    from .mdns import MDNS
  File "/usr/local/lib/python2.7/dist-packages/netdisco/mdns.py", line 2, in <module>
    import zeroconf
  File "/usr/local/lib/python2.7/dist-packages/zeroconf/__init__.py", line 220
    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax
```
Adding "enp0s25" as a parameter is making no difference in the result.

**Comment by nicholasphair** [comment]
Looks like you are using python2.7 and python3 is required.

This was an upstream issue too :) https://github.com/jstasiak/python-zeroconf/issues/182
