### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'

### ISSUE THREAD

**Issue by dbl001** [nyu-mlab/iot-inspector-client#110]
I am running with an Anaconda Python 3.8.5 stack in a virtual environment.

% ulimit -n
256

Here's the exception:
```
 sudo python start_inspector.py
net.inet.ip.forwarding: 1 -> 1







































































































======================================
Princeton IoT Inspector for Windows 10
======================================

We have also opened a new browser window for you to view the IoT Inspector report. If you don't see a new browser window, use the following private link:

https://dashboard.iotinspector.org/user/XAcT-KXC8-2mGQ-eTdw

To stop IoT Inspector, simply close this window or hit Control + C.

Questions? Email us at iot-inspector@lists.cs.princeton.edu.


================================================================================
Time: 2021-08-07 08:16:07.800537
Function: <bound method NetdiscoWrapper._run_netdisco of <netdisco_wrapper.NetdiscoWrapper object at 0x7fd9d066a9d0>> [] {}
Exception: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 252, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/netdisco_wrapper.py", line 54, in _run_netdisco
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/discovery.py", line 67, in scan
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/gdm.py", line 23, in scan
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/gdm.py", line 70, in update
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/socket.py", line 231, in __init__
OSError: [Errno 24] Too many open files




Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 252, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/netdisco_wrapper.py", line 54, in _run_netdisco
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/discovery.py", line 67, in scan
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/gdm.py", line 23, in scan
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/netdisco/gdm.py", line 70, in update
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/socket.py", line 231, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 870, in run
  File "/Users/davidlaxer/iot-inspector-client/src/netdisco_wrapper.py", line 40, in _start_thread
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 264, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 870, in run
  File "/Users/davidlaxer/iot-inspector-client/src/arp_spoof.py", line 85, in _arp_spoof_loop
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'
================================================================================
Time: 2021-08-07 08:16:10.931710
Function: <bound method DataUploader._upload_data of <data_upload.DataUploader object at 0x7fda203b4580>> [] {}
Exception: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'
Traceback (most recent call last):
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 252, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/data_upload.py", line 237, in _upload_data
    utils.log('[UPLOAD]', status_text)
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'




Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 252, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/data_upload.py", line 237, in _upload_data
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/threading.py", line 870, in run
  File "/Users/davidlaxer/iot-inspector-client/src/data_upload.py", line 77, in _upload_thread
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 264, in safe_run
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'
^C
Traceback (most recent call last):
  File "start_inspector.py", line 137, in <module>
  File "start_inspector.py", line 67, in main
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 103, in log
OSError: [Errno 24] Too many open files: '/Users/davidlaxer/princeton-iot-inspector/iot_inspector_logs.txt'
```
Here's the log file:
"~/princeton-iot-inspector/iot_inspector_logs.txt" [readonly] 48043L, 3671683B
```
[2021-05-20 11:04:42.543845] [Main] Starting inspector.
[2021-05-20 11:04:43.126873] [MAIN] Starting.
[2021-05-20 11:04:43.253432] Initialized: {'host_ip': '10.0.1.28', 'host_mac': '88:66:5a:09:45:ee', 'gateway_ip': '10.0.1.1', 'packet_processor': <packet_processor.PacketProcessor object at 0x7ffde019c070>, 'user_key': 'XAcTKXC82mGQeTdw', 'secret_salt': '1d782bef-7cb5-451a-8242-b62a2fb278db', 'client_version': '1.0.3', 'persistent_mode': True, 'raspberry_pi_mode': False, 'lock': <unlocked _thread.lock object at 0x7ffde0184f90>, 'ip_mac_dict': {}, 'pending_dhcp_dict': {}, 'pending_resolver_dict': {}, 'pending_dns_dict': {}, 'pending_flow_dict': {}, 'pending_ua_dict': {}, 'pending_tls_dict_list': [], 'pending_netdisco_dict': {}, 'pending_syn_scan_dict': {}, 'status_text': None, 'device_whitelist': [], 'has_consent': False, 'byte_count': 0, 'is_inspecting_traffic': True, 'fast_arp_scan': True, 'last_ui_contact_ts': 1621533883.127053, 'quit': False, 'spoof_arp': True}
[2021-05-20 11:04:43.253730] [ARP Scanning] Starting.
[2021-05-20 11:04:43.254391] [SYN Scanning] Starting.
[2021-05-20 11:04:43.256968] [Packet Capture] Starting.
[2021-05-20 11:04:43.257352] [Arp Spoof] Starting.
[2021-05-20 11:04:43.257648] [DATA] Update UTC offset: https://dashboard.iotinspector.org/submit_utc_offset/XAcTKXC82mGQeTdw/-25200
[2021-05-20 11:04:43.257680] [Data] Start uploading data.
[2021-05-20 11:04:44.025003] [DATA] Update UTC offset status: SUCCESS
[2021-05-20 11:04:44.025527] [DATA] Update UI: Continuously analyzing your network.

```
Here's my environment:
```
% pip list
Package                           Version             Location
--------------------------------- ------------------- ---------------------------------------------------------------
absl-py                           0.12.0
anyio                             3.3.0
appnope                           0.1.0
argon2-cffi                       20.1.0
astunparse                        1.6.3
async-generator                   1.10
attrs                             20.2.0
Babel                             2.8.0
backcall                          0.2.0
bleach                            3.2.1
blis                              0.4.1
boto3                             1.17.86
botocore                          1.20.86
brotlipy                          0.7.0
cachetools                        4.2.2
catalogue                         1.0.0
cdt                               0.5.23              /Users/davidlaxer/CausalDiscoveryToolbox
certifi                           2020.6.20
cffi                              1.14.3
chainer                           6.3.0
chardet                           4.0.0
click                             8.0.1
cloudpickle                       1.6.0
cryptography                      3.1.1
cycler                            0.10.0
cymem                             2.0.5
Cython                            0.29.23
decorator                         4.4.2
defusedxml                        0.6.0
dill                              0.3.4
dm-sonnet                         2.0.0
dm-tree                           0.1.6
dopamine-rl                       3.0.1
dotmap                            1.3.24
en-trf-bertbaseuncased-lg         2.3.0
entrypoints                       0.3
filelock                          3.0.12
findspark                         1.3.0
flatbuffers                       1.12
ftfy                              5.9
future                            0.18.2
gast                              0.4.0
gdown                             3.13.0
gensim                            3.8.3
glob2                             0.7
google-auth                       1.30.1
google-auth-oauthlib              0.4.4
google-pasta                      0.2.0
GPUtil                            1.4.0
grpcio                            1.34.1
gviz-api                          1.9.0
h5py                              3.1.0
hdbscan                           0.8.27
hnswlib                           0.5.1
huggingface-hub                   0.0.8
idna                              2.10
ifaddr                            0.1.7
imageio                           2.9.0
importlib-metadata                2.0.0
importlib-resources               5.1.4
ipykernel                         5.3.4
ipython                           7.18.1
ipython-genutils                  0.2.0
jedi                              0.18.0
Jinja2                            2.11.2
jmespath                          0.10.0
joblib                            1.0.1
json5                             0.9.5
jsonlines                         2.0.0
jsonschema                        3.2.0
jupyter-client                    6.1.7
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.10.2
jupyterlab                        2.2.6
jupyterlab-pygments               0.1.2
jupyterlab-server                 1.2.0
keras-nightly                     2.5.0.dev2021032900
Keras-Preprocessing               1.1.2
kiwisolver                        1.3.1
librosa                           0.7.2
llvmlite                          0.36.0
lxml                              4.6.1
magenta                           2.1.3               /Users/davidlaxer/magenta
Markdown                          3.3.4
MarkupSafe                        1.1.1
matplotlib                        3.4.2
memory-profiler                   0.58.0
mido                              1.2.6
mir-eval                          0.6
mistune                           0.8.4
mkl-fft                           1.2.0
mkl-random                        1.1.1
mkl-service                       2.3.0
murmurhash                        1.0.5
nbclassic                         0.3.1
nbclient                          0.5.1
nbconvert                         6.0.7
nbformat                          5.0.8
nest-asyncio                      1.4.1
netaddr                           0.8.0
netdisco                          2.9.0
netifaces                         0.11.0
networkx                          2.6rc1
nltk                              3.6.2
note-seq                          0.0.3
notebook                          6.1.4
numba                             0.53.1
numpy                             1.20.3
oauthlib                          3.1.0
olefile                           0.46
opt-einsum                        3.3.0
packaging                         20.4
pandas                            1.2.4
pandocfilters                     1.4.2
parso                             0.8.0
pathlib2                          2.3.5
patsy                             0.5.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            8.2.0
pip                               20.2.4
plac                              1.1.3
preshed                           3.0.5
pretty-midi                       0.2.9
prettytable                       2.1.0
prometheus-client                 0.8.0
promise                           2.3
prompt-toolkit                    3.0.8
protobuf                          3.17.1
psutil                            5.7.2
ptyprocess                        0.6.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycparser                         2.20
Pygments                          2.7.1
pygtrie                           2.4.2
pynndescent                       0.5.2
pyOpenSSL                         19.1.0
pyparsing                         2.4.7
pyrsistent                        0.17.3
PySocks                           1.7.1
python-dateutil                   2.8.1
python-rtmidi                     1.1.2
pytokenizations                   0.8.3
pytorch-pretrained-bert           0.6.2
pytorch-transformers              1.2.0
pytz                              2021.1
PyYAML                            5.3.1
pyzmq                             19.0.2
regex                             2021.4.4
requests                          2.25.1
requests-oauthlib                 1.3.0
requests-unixsocket               0.2.0
rsa                               4.7.2
s3transfer                        0.4.2
sacremoses                        0.0.45
scapy                             2.4.3
scikit-image                      0.18.2rc2
scikit-learn                      0.24.2
scipy                             1.6.3
Send2Trash                        1.5.0
sentence-transformers             1.2.0               /Users/davidlaxer/sentence-transformers
sentencepiece                     0.1.95
setuptools                        50.3.0.post20201006
six                               1.15.0
sk-video                          1.1.10
skrebate                          0.62
smart-open                        5.1.0
sniffio                           1.1.0
sox                               1.4.1
spacy                             2.3.6
spacy-transformers                0.6.2
srsly                             1.0.5
statsmodels                       0.12.2
stop-words                        2018.7.23
tagme                             0.1.3
tensor2tensor                     1.15.7
tensorboard                       2.5.0
tensorboard-data-server           0.6.1
tensorboard-plugin-profile        2.4.0
tensorboard-plugin-wit            1.8.0
tensorflow                        2.5.0
tensorflow-datasets               4.3.0
tensorflow-estimator              2.5.0
tensorflow-hub                    0.12.0
tensorflow-metadata               1.0.0
tensorflow-probability            0.13.0rc0
tensorflow-text                   2.5.0
termcolor                         1.1.0
terminado                         0.9.1
testpath                          0.4.4
tf-slim                           1.1.0
thinc                             7.4.5
threadpoolctl                     2.1.0
tokenizers                        0.5.2
top2vec                           1.0.24
torch                             1.8.1
torchcontrib                      0.0.2
torchvision                       0.9.1
tornado                           6.1
tqdm                              4.61.0
traitlets                         5.0.5
transformers                      2.8.0               /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages
typing-extensions                 3.7.4.3
ujson                             4.0.2
umap-learn                        0.5.1
unicodecsv                        0.14.1
urllib3                           1.26.5
wasabi                            0.8.2
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  0.57.0
Werkzeug                          2.0.1
wheel                             0.36.2
wordcloud                         1.8.1
wrapt                             1.12.1
zeroconf                          0.33.2
zipp                              3.3.1

```

**Comment by dbl001** [comment]
I adjusted the maxfiles
E.g.
<img width="2560" alt="Screen Shot 2021-08-15 at 12 09 18 PM" src="https://user-images.githubusercontent.com/3105499/129489728-9d3b945e-880e-4f44-884f-a484e28d6b6f.png">

```
% sudo sysctl kern.maxfiles=64000 kern.maxfilesperproc=28000
Password:
kern.maxfiles: 196608 -> 64000
kern.maxfilesperproc: 98304 -> 28000
(base) davidlaxer@x86_64-apple-darwin13 pytorch % sysctl -a | grep maxfiles
kern.maxfiles: 64000
kern.maxfilesperproc: 28000

```
it ran for a while but then got this exception:
```
$ sudo python start_inspector.py
...

Time: 2021-08-15 12:06:39.901746
Function: <function sniff at 0x7f9c8005f280> [] {'prn': <bound method PacketProcessor.process_packet of <packet_processor.PacketProcessor object at 0x7f9ca16d5af0>>, 'stop_filter': <function PacketCapture._capture_packets.<locals>.<lambda> at 0x7f9cb33590d0>, 'timeout': 30}
Exception: filedescriptor out of range in select()
Traceback (most recent call last):
  File "/Users/davidlaxer/iot-inspector-client/src/utils.py", line 254, in safe_run
    return func(*args, **kwargs)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/scapy/sendrecv.py", line 893, in _run
    sockets, read_func = select_func(sniff_sockets, remain)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 226, in select
    return bpf_select(sockets, remain), None
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 397, in bpf_select
    ready_list, _, _ = select(select_fds, [], [], timeout)
ValueError: filedescriptor out of range in select()

```

**Comment by william1357chen** [comment]
I also have the same problem and I believe I found the fix. The `netdisco` thread keeps on opening sockets without calling `netdis.stop()` which caused this error. I will commit a fix to this issue soon.

**Comment by dbl001** [comment]
I can confirm that this issue is fixed.
Question: is there a way to see the IP Addresses of end-points with question mark (other then using WireShark)?
E.g. ? 
(184.26.128.32 and 9 others)

**Comment by crazyideas21** [comment]
Will be in the next major release. It's a difficult issue as sometimes we don't see DNS packets.

The next major release will infer FQDNs based on SNIs. Currently, the ClientHello parsing is broken.

**Comment by crazyideas21** [comment]
Good point. Will communicate with the UI UX team

**Comment by william1357chen** [comment]
Additionally, endpoints within the LAN are classified as ? even though they should get the device name of that IP address. For instance, a phone talking to Chromecast at 192.168.0.128 should get it’s communication endpoint to 192.168.0.128 classified as the device name of 192.168.0.128.

**Comment by dbl001** [comment]
Also, if a VPN is activated on the device being scanned, all activity is grouped under ‘?’.
Are the communication end-point IP addresses encrypted (and are therefore hidden) by the VPN to IOT Inspector?
It appears that most of the network activity is not detected with the VPN is active.

**Comment by william1357chen** [comment]
Yeah, that's the whole point of using a VPN; to encapsulate the packets. So it's not possible to see the actual endpoints, only the endpoint of the VPN server.

**Comment by dbl001** [comment]
Two questions:
1. can IoT Inspector coexist with Firewalla Purple?
2. ETA on new IoT Inspector release?
