### ISSUE TITLE
Princeton IoT inspector will not run

### ISSUE THREAD

**Issue by vlstice** [nyu-mlab/iot-inspector-client#27]
Hello,

No matter how many times I attempt it or open in a new Firefox or Chrome window, the inspector will not run or refresh. This is as far as I can get.
![Screen Shot 2019-10-07 at 8 38 37 AM](https://user-images.githubusercontent.com/46907498/66316815-f35ebf00-e8dd-11e9-9d0b-79b043f77bb5.png)

Thank you

**Comment by amitashukla** [comment]
I am having the same issue. 

Start_inspector_mac gives the following error output:

Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "inspector.py", line 5, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "utils.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "scapy/all.py", line 25, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "scapy/route.py", line 162, in <module>
  File "scapy/route.py", line 22, in __init__
  File "scapy/route.py", line 31, in resync
  File "scapy/arch/unix.py", line 65, in read_routes
IndexError: list index out of range
[12764] Failed to execute script start_inspector
logout
